blog/urls.py
from django.urls import path

from blog.views import Posts, SinglePost, PostComment

app_name = 'blog'

urlpatterns = [
    path('search/', Posts.as_view(), name="search"),
    path('post/<str:slug>/add_comment/', PostComment.as_view(), name="add-comment"),
    path('post/<str:slug>/', SinglePost.as_view(), name="detail"),
    path('<str:type>/<str:slug>/', Posts.as_view(), name="filter"),
    path('', Posts.as_view(), name="list"),
]

djangosample/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('', include('blog.urls', namespace='blog'))
]

user/urls.py
from django.urls import path

from user.views import Login, Logout, Register

app_name = 'user'

urlpatterns = [
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('register/', Register.as_view(), name="register"),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _


class Category(models.Model):
    name = models.CharField(_('Category'), max_length=255)
    slug = models.SlugField(_('Slug'))

    def __str__(self):
        return self.name


class PostManager(models.Manager):
    """
    Only display Active posts instead everything.
    """

    def for_display(self):
        return super(PostManager, self).get_queryset().filter(active=True)


class Post(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'))
    content = models.TextField(_('Content'))
    posted_by = models.ForeignKey(User, verbose_name=_('Posted by'), on_delete=models.PROTECT)
    posted_on = models.DateTimeField(auto_now_add=True, verbose_name=_('Posted on'))
    categories = models.ManyToManyField(Category, verbose_name=_('Categories'), blank=True)
    active = models.BooleanField(_('Active'), default=False)
    objects = PostManager()

    def __str__(self):
        return _('%s by %s') % (self.title, self.posted_by.get_full_name())

    class Meta:
        ordering = ['-posted_on', '-pk']


class Comment(models.Model):
    text = models.TextField(_('Comment'))
    posted_by = models.ForeignKey(User, verbose_name=_('Posted by'), on_delete=models.PROTECT)
    posted_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, verbose_name='Post', related_name='comments', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-posted_on']

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView

from blog.models import Post, Comment


class Posts(ListView):
    """
    Display every post paginated or if given a type filter/search for it.
    """
    model = Post
    template_name = 'posts.html'
    paginate_by = 5

    def get_queryset(self):
        qs = self.model.objects.for_display()
        type_of_page = self.kwargs.get('type', False)
        search_query = self.request.GET.get('q', False)
        if type_of_page == 'user':
            qs = qs.filter(posted_by__username=self.kwargs.get('slug', ''))
        elif type_of_page == 'category':
            qs = qs.filter(categories__slug=self.kwargs.get('slug', ''))
        if search_query:
            qs = qs.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query))
        return qs


class SinglePost(DetailView):
    """
    Display a single selected post.
    """
    model = Post
    template_name = 'post.html'

    def get_queryset(self):
        return self.model.objects.for_display()


class PostComment(CreateView):
    """
    Saves comments received to a post. Removed ability to GET the page.
    """
    model = Comment
    fields = ['text']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(PostComment, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse('blog:detail', kwargs={'slug': self.kwargs['slug']}))

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.posted_by = self.request.user
        comment.post = get_object_or_404(Post, slug=self.kwargs['slug'])
        comment.save()
        messages.success(self.request, 'Your comment was posted.')
        return super(PostComment, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'slug': self.kwargs['slug']})

user/views.py
from django import forms
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import modelform_factory
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, RedirectView, CreateView


class Login(FormView):
    """
    Logs in the user then redirects him back to home or back to the page he came from.
    """
    form_class = AuthenticationForm
    template_name = 'login.html'

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(Login, self).form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next', False)
        redirect_to = reverse('blog:list') if not next_url else next_url
        return redirect_to

    def get_context_data(self, **kwargs):
        context = super(Login, self).get_context_data(**kwargs)
        context['current_page'] = 'login'
        return context


class Logout(RedirectView):
    """
    Logs out the currently logged in user.
    """
    permanent = False
    url = reverse_lazy('blog:list')

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super(Logout, self).dispatch(request, *args, **kwargs)


class Register(CreateView):
    """
    Page for handling user sign ups.
    """
    model = User
    fields = ['username', 'password', 'first_name', 'last_name']
    success_url = reverse_lazy('user:login')
    template_name = 'register.html'
    widgets = {
        'password': forms.PasswordInput
    }

    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields, widgets=self.widgets)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        return super(Register, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Register, self).get_context_data(**kwargs)
        context['current_page'] = 'register'
        return context

blog/templates/post.html
{% extends 'base.html' %}{% load i18n %}
{% block content %}
    <div class="col-md-8">
        <h1 class="page-header">
            {% trans 'Blog' %}
            <small>{% trans 'Amazing content' %}</small>
        </h1>
        {% include 'single-post.html' %}
    </div>
{% endblock %}

blog/templates/posts.html
{% extends 'base.html' %}{% load i18n %}
{% block content %}
    <div class="col-md-8">
        <h1 class="page-header">
            {% trans 'Blog' %}
            <small>{% trans 'Amazing content' %}</small>
        </h1>
        {% for object in object_list %}
            {% with multiple=True %}
                {% include 'single-post.html' %}
            {% endwith %}
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% empty %}
            {% trans 'No post could be found.' %}
        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
            <ul class="pager">
                {% if page_obj.has_next %}
                    <li class="previous">
                        <a href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
                    </li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li class="next">
                        <a href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

blog/templates/single-post.html
{% load i18n humanize %}

{% if multiple %}
    <h2><a href="{% url 'blog:detail' object.slug %}">{{ object.title }}</a></h2>
{% else %}
    <h2>{{ object.title }}</h2>
{% endif %}

<p class="lead"> by
    <a href="{% url 'blog:filter' 'user' object.posted_by.username %}">{{ object.posted_by.get_full_name }}</a></p><p>
    <span class="glyphicon glyphicon-time"></span> Posted {{ object.posted_on|naturaltime }}
    {% if multiple %}
        |<a href="{% url 'blog:detail' object.slug %}#comments">
        {% blocktrans with count=object.comments.count plur=object.comments.count|pluralize %}{{ count }} comment{{ plur }}{% endblocktrans %}</a>
    {% endif %}
</p>
<hr>
{% if multiple %}
    <p>{{ object.content|truncatewords_html:50 }}</p>
    <a class="btn btn-primary btn-xs" href="{% url 'blog:detail' object.slug %}">{% trans 'Read More' %}
        <span class="glyphicon glyphicon-chevron-right"></span></a>
{% else %}
    <p>{{ object.content|linebreaks }}</p>
    <hr />
    {% if user.is_authenticated %}
        <div class="well" id="comments">
            <h4>{% trans 'Leave a Comment' %}:</h4>

            <form role="form" action="{% url 'blog:add-comment' object.slug %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <textarea class="form-control" rows="3" name="text"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
            </form>
        </div>
    {% else %}
        <div class="well" id="comments">
            {% url 'user:login' as login_url %}
            <h4>{% blocktrans with login_url=login_url %} You must <a href="{{ login_url }}">login</a> before being able to comment. {% endblocktrans %}</h4>
        </div>
    {% endif %}
    {% for comment in object.comments.all %}
        <div class="media">
            <a class="pull-left" href="#"> <img class="media-object" src="http://placehold.it/64x64" alt=""> </a>
            <div class="media-body">
                <h4 class="media-heading">{{ comment.posted_by.get_full_name }}
                    <small>{{ comment.posted_on|naturaltime }}</small>
                </h4>
                {{ comment.text }}
            </div>
        </div>

    {% endfor %}
{% endif %}

templates/base.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{% trans 'Sample django application' %}">
        <meta name="author" content="Richard Hajdu">
        <title>SampleBlog</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/default.css' %}" rel="stylesheet">
        {% block extra_css %}{% endblock %}<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                        <span class="icon-bar"></span> <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'blog:list' %}">SampleBlog</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li{% if not current_page %} class="active"{% endif %}>
                            <a href="{% url 'blog:list' %}">{% trans 'Blog' %}</a>
                        </li>
                        {% if user.is_authenticated %}
                            {% if user.is_staff %}
                                <li>
                                    <a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'user:logout' %}">{% trans 'Logout' %}</a>
                            </li>
                        {% else %}
                            <li{% ifequal current_page 'login' %} class="active"{% endifequal %}>
                                <a href="{% url 'user:login' %}">{% trans 'Login' %}</a>
                            </li>
                            <li{% ifequal current_page 'register' %} class="active"{% endifequal %}>
                                <a href="{% url 'user:register' %}">{% trans 'Register' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <!-- Page Content -->
        <div class="container">
            <div class="row">
                {% for message in messages %}
                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <strong>{{ message.tags|capfirst }}!</strong> {{ message }}
                    </div>
                {% endfor %}
                {% block content %}{% endblock %}
                <div class="col-md-4">
                    <div class="well">
                        <h4>{% trans 'Blog Search' %}</h4>

                        <form method="get" action="{% url 'blog:search' %}">
                            <div class="input-group">
                                <input type="search" name="q" class="form-control" title="Search">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="well">
                        <h4>{% trans 'Blog Categories' %}</h4>
                        <div class="row">
                            <ul class="list-unstyled">
                                {% for category in categories %}
                                    <li class="col-lg-6">
                                        <a href="{% url 'blog:filter' 'category' category.slug %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            <!-- /.col-lg-6 -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- Side Widget Well -->
                    <div class="well">
                        <h4>SampleBlog</h4>
                        <p>
                            {% blocktrans %}Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.{% endblocktrans %}
                        </p>
                    </div>
                </div>
            </div>
            <hr>
            <!-- Blog Sidebar Widgets Column --><!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>&copy; Richard Hajdu 2015-2018</p>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </footer>
        </div>
        <!-- /.container --><!-- jQuery -->
        <script src="{% static 'js/jquery.js' %}"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block extra_js %}{% endblock %}
    </body>
</html>

templates/login.html
{% extends 'base.html' %}{% load bootstrap3 %}
{% block content %}
    <div class="col-md-8">
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %} {% bootstrap_button 'Send' 'submit' %}
        </form>
    </div>
{% endblock %}

user/templates/login.html
{% extends 'base.html' %}{% load bootstrap4 %}
{% block content %}
    <div class="col-md-8">
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button 'Login' 'submit' %}
        </form>
    </div>
{% endblock %}

user/templates/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="col-md-8">
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %} {% bootstrap_button 'Register' 'submit' %}
        </form>
    </div>
{% endblock %}